# Generated by Django 3.2.5 on 2021-07-15 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='mountain_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='mountain_range',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Climber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climber_name', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mountain',
            name='climber',
            field=models.ManyToManyField(to='main.Climber'),
        ),
    ]
