# Generated by Django 3.2.5 on 2021-07-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210715_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountain',
            name='climber',
        ),
        migrations.AddField(
            model_name='climber',
            name='ascents',
            field=models.ManyToManyField(to='main.Mountain'),
        ),
    ]
