# Generated by Django 3.2.5 on 2021-07-16 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_climber_ascents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climber',
            name='ascents',
        ),
        migrations.CreateModel(
            name='Ascents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.climber')),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mountain')),
            ],
        ),
        migrations.AddField(
            model_name='climber',
            name='mountains',
            field=models.ManyToManyField(through='main.Ascents', to='main.Mountain'),
        ),
        migrations.AddField(
            model_name='mountain',
            name='climbers',
            field=models.ManyToManyField(through='main.Ascents', to='main.Climber'),
        ),
    ]
